spring:
  application:
    name: GreengramVer1
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/greengram2024_v1
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_v1
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 5MB


mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger # Swagger page? redirect
    operations-sorter: method #alpha(default): url ?? ??, method: http-method ?? ??
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true # try it out ? ?? ? request duration(?? ????) ? ??? ???
    cache:
      disabled: true

file:
  directory: D:\2024-01\download\greengram_ver1\




---

spring:
  config:
    activate:
      on-profile: test



file:
  directory: D:\download\greengram_ver1\




